// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hash.proto

/*
Package go_micro_srv_hash is a generated protocol buffer package.

It is generated from these files:
	hash.proto

It has these top-level messages:
	SHA256Request
	SHA256Response
*/
package hash

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Hash service

type HashService interface {
	SHA256(ctx context.Context, in *SHA256Request, opts ...client.CallOption) (*SHA256Response, error)
}

type hashService struct {
	c    client.Client
	name string
}

func NewHashService(name string, c client.Client) HashService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.hash"
	}
	return &hashService{
		c:    c,
		name: name,
	}
}

func (c *hashService) SHA256(ctx context.Context, in *SHA256Request, opts ...client.CallOption) (*SHA256Response, error) {
	req := c.c.NewRequest(c.name, "Hash.SHA256", in)
	out := new(SHA256Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hash service

type HashHandler interface {
	SHA256(context.Context, *SHA256Request, *SHA256Response) error
}

func RegisterHashHandler(s server.Server, hdlr HashHandler, opts ...server.HandlerOption) error {
	type hash interface {
		SHA256(ctx context.Context, in *SHA256Request, out *SHA256Response) error
	}
	type Hash struct {
		hash
	}
	h := &hashHandler{hdlr}
	return s.Handle(s.NewHandler(&Hash{h}, opts...))
}

type hashHandler struct {
	HashHandler
}

func (h *hashHandler) SHA256(ctx context.Context, in *SHA256Request, out *SHA256Response) error {
	return h.HashHandler.SHA256(ctx, in, out)
}
