// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hash.proto

package hash

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SHA256Request struct {
	Str                  string   `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SHA256Request) Reset()         { *m = SHA256Request{} }
func (m *SHA256Request) String() string { return proto.CompactTextString(m) }
func (*SHA256Request) ProtoMessage()    {}
func (*SHA256Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_844ef095867f6a46, []int{0}
}

func (m *SHA256Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SHA256Request.Unmarshal(m, b)
}
func (m *SHA256Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SHA256Request.Marshal(b, m, deterministic)
}
func (m *SHA256Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SHA256Request.Merge(m, src)
}
func (m *SHA256Request) XXX_Size() int {
	return xxx_messageInfo_SHA256Request.Size(m)
}
func (m *SHA256Request) XXX_DiscardUnknown() {
	xxx_messageInfo_SHA256Request.DiscardUnknown(m)
}

var xxx_messageInfo_SHA256Request proto.InternalMessageInfo

func (m *SHA256Request) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

type SHA256Response struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SHA256Response) Reset()         { *m = SHA256Response{} }
func (m *SHA256Response) String() string { return proto.CompactTextString(m) }
func (*SHA256Response) ProtoMessage()    {}
func (*SHA256Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_844ef095867f6a46, []int{1}
}

func (m *SHA256Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SHA256Response.Unmarshal(m, b)
}
func (m *SHA256Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SHA256Response.Marshal(b, m, deterministic)
}
func (m *SHA256Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SHA256Response.Merge(m, src)
}
func (m *SHA256Response) XXX_Size() int {
	return xxx_messageInfo_SHA256Response.Size(m)
}
func (m *SHA256Response) XXX_DiscardUnknown() {
	xxx_messageInfo_SHA256Response.DiscardUnknown(m)
}

var xxx_messageInfo_SHA256Response proto.InternalMessageInfo

func (m *SHA256Response) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*SHA256Request)(nil), "go.micro.srv.hash.SHA256Request")
	proto.RegisterType((*SHA256Response)(nil), "go.micro.srv.hash.SHA256Response")
}

func init() { proto.RegisterFile("hash.proto", fileDescriptor_844ef095867f6a46) }

var fileDescriptor_844ef095867f6a46 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x48, 0x2c, 0xce,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4c, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca,
	0xd7, 0x2b, 0x2e, 0x2a, 0xd3, 0x03, 0x49, 0x28, 0x29, 0x72, 0xf1, 0x06, 0x7b, 0x38, 0x1a, 0x99,
	0x9a, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x70, 0x31, 0x17, 0x97, 0x14, 0x49,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4a, 0x2a, 0x5c, 0x7c, 0x30, 0x25, 0xc5, 0x05,
	0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x20, 0xcd, 0x50, 0x45, 0x60, 0xb6, 0x51, 0x38,
	0x17, 0x8b, 0x47, 0x62, 0x71, 0x86, 0x90, 0x3f, 0x17, 0x1b, 0x44, 0xb5, 0x90, 0x82, 0x1e, 0x86,
	0x75, 0x7a, 0x28, 0x76, 0x49, 0x29, 0xe2, 0x51, 0x01, 0xb1, 0x4a, 0x89, 0x21, 0x89, 0x0d, 0xec,
	0x76, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0xa1, 0x56, 0x1e, 0xc9, 0x00, 0x00, 0x00,
}
